spring:
  swagger:
    enabled: true
    title: 康桥医图微服务
    description: 康桥医图微服务接口
    version: 1.0
    security:
      filter-plugin: true
      username: conque
      password: 1qaz2wsx
    global-operation-parameters:
        -   description: 'Token信息,必填项'
            modelRef: 'string'
            name: 'Authorization'
            parameter-type: 'header'
            required: true
    contact:
      name: conque@conque.cn
  dubbo:
    application:
      name: consumer
      base-package: cn.conque.consumer.system.controller  # dubbo服务调用者所在的包
    registry:
      address: 127.0.0.1                   # zookeeper注册中心的地址
      port: 2181                           # zookeeper注册中心的端口
    consumer:
      timeout: 1000
      check: true                          # 服务启动时检查被调用服务是否可用
      retries: 2                           # 服务调用重试次数
server:
  port: 8070

##jwt配置
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800