server:
  port: 8087
  address: 127.0.0.1
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

org:
    dromara:
         hmily :
            serializer : kryo
            recoverDelayTime : 128
            retryMax : 30
            scheduledDelay : 128
            scheduledThreadMax :  10
            repositorySupport : db
            started: true
            async-threads: 200
            hmilyDbConfig :
                 driverClassName  : com.mysql.cj.jdbc.Driver
                 url :  jdbc:mysql://127.0.0.1:3306/tcc?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
                 username : root
                 password : root

        #repositorySupport : redis
        #tccRedisConfig:
                # masterName: mymaster
                 #sentinel : true
                 #sentinelUrl : 192.168.1.91:26379;192.168.1.92:26379;192.168.1.93:26379
                # password  : foobaredbbexONE123

mybatis:
  type-aliases-package: com.hmily.tcc.demo.dubbo.order.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.dromara.hmily.bonuspoint: info
        org.dromara.hmily.lottery: info
        org.dromara.hmily: info
        io.netty: info
    path: "./logs"

  # dubbo配置
  dubbo:
    application:
      name: order
    base-package: org.dromara.hmily.demo.dubbo.order.service  # dubbo服务发布者所在的包
    registry:
      address: 127.0.0.1                   # zookeeper注册中心的地址
      port: 2181                           # zookeeper注册中心的端口
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0                           # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试